apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifact-id:
        type: string
        required: true
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: mlcb-label-test
          artifact-id: ${{ inputs.artifact-id }}
          target-environment: TestEnvMLCB
